# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_topic_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oppurtunities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('type', models.CharField(choices=[('govt', 'GOVT'), ('private', 'PRIVATE')], default='govt', max_length=7)),
                ('brief_info', models.TextField(max_length=1000)),
                ('age_criteria', models.IntegerField()),
                ('gender_criteria', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('both', 'BOTH')], default='both', max_length=6)),
            ],
        ),
    ]
